liip_imagine:
  #    # valid drivers options include "gd" or "gmagick" or "imagick"
  #    driver: "gd"
  #
  #    # define your filter sets under this option
  filter_sets:
    #
    #        # an example thumbnail transformation definition
    #        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
    squared_thumbnail_small:
      filters:
        thumbnail:
          size:          [200, 200]
          mode:          outbound
          allow_upscale: true
    squared_thumbnail_medium:
      filters:
        thumbnail:
          size: [ 500, 500 ]
          mode: outbound
          allow_upscale: true
